load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//bzl:copts.bzl", "RAMA_COPTS")

cc_library(
    name = "ende",
    hdrs = ["ende.h"],
    copts = RAMA_COPTS,
    visibility = ["//visibility:public"],
)

cc_test(
    name = "ende_test",
    srcs = ["ende_test.cc"],
    copts = RAMA_COPTS,
    deps = [
        ":ende",
        "@hastur//etest",
    ],
)
